<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <Import Project="..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <RootNamespace>hanhchinhso.Blazor.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac.WebAssembly" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
  </ItemGroup>

  <ItemGroup>
      <EmbeddedResource Include="Localization\hanhchinhso\*.json" />
      <Content Remove="Localization\hanhchinhso\*.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly.MudBlazorLeptonXTheme" Version="5.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Account.Pro.Admin.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.Account.Pro.Public.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.Identity.Pro.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <ProjectReference Include="../../../services/ai-management/hanhchinhso.AIManagementService.Contracts/hanhchinhso.AIManagementService.Contracts.csproj" />
    <PackageReference Include="Volo.AIManagement.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <PackageReference Include="Volo.AIManagement.Client.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.TextTemplateManagement.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <ProjectReference Include="../../../services/audit-logging/hanhchinhso.AuditLoggingService.Contracts/hanhchinhso.AuditLoggingService.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.AuditLogging.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <ProjectReference Include="../../../services/language/hanhchinhso.LanguageService.Contracts/hanhchinhso.LanguageService.Contracts.csproj" />
    <ProjectReference Include="../../../services/organization/hanhchinhso.OrganizationService.Contracts/hanhchinhso.OrganizationService.Contracts.csproj" />
    <ProjectReference Include="../../../services/document/hanhchinhso.DocumentService.Contracts/hanhchinhso.DocumentService.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.Http.Client" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.LanguageManagement.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.OpenIddict.Pro.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <ProjectReference Include="../../../services/gdpr/hanhchinhso.GdprService.Contracts/hanhchinhso.GdprService.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.Gdpr.Blazor.MudBlazor.WebAssembly" Version="10.5.0" />
    <ProjectReference Include="../../../services/identity/hanhchinhso.IdentityService.Contracts/hanhchinhso.IdentityService.Contracts.csproj" />
    <ProjectReference Include="../../../services/administration/hanhchinhso.AdministrationService.Contracts/hanhchinhso.AdministrationService.Contracts.csproj" />
  </ItemGroup>


  <ItemGroup>
      <EmbeddedResource Include="**\*generate-proxy.json"/>
      <Content Remove="**\*generate-proxy.json"/>
  </ItemGroup>
</Project>
