import type { DirectusActivity } from './activity.js';
import type { DirectusCollection } from './collection.js';
import type { DirectusComment } from './comment.js';
import type { DirectusDashboard } from './dashboard.js';
import type { DirectusExtension } from './extension.js';
import type { DirectusField } from './field.js';
import type { DirectusFile } from './file.js';
import type { DirectusFlow } from './flow.js';
import type { DirectusFolder } from './folder.js';
import type { DirectusNotification } from './notification.js';
import type { DirectusOperation } from './operation.js';
import type { DirectusPanel } from './panel.js';
import type { DirectusPermission } from './permission.js';
import type { DirectusPreset } from './preset.js';
import type { DirectusRelation } from './relation.js';
import type { DirectusRole } from './role.js';
import type { DirectusSettings } from './settings.js';
import type { DirectusShare } from './share.js';
import type { DirectusUser } from './user.js';
import type { DirectusVersion } from './version.js';

export interface CoreSchema<Schema = any> {
	axis_activity: DirectusActivity<Schema>[];
	axis_collections: DirectusCollection<Schema>[];
	axis_comments: DirectusComment<Schema>[];
	axis_dashboards: DirectusDashboard<Schema>[];
	axis_extensions: DirectusExtension<Schema>[];
	axis_fields: DirectusField<Schema>[];
	axis_files: DirectusFile<Schema>[];
	axis_flows: DirectusFlow<Schema>[];
	axis_folders: DirectusFolder<Schema>[];
	axis_notifications: DirectusNotification<Schema>[];
	axis_operations: DirectusOperation<Schema>[];
	axis_panels: DirectusPanel<Schema>[];
	axis_permissions: DirectusPermission<Schema>[];
	axis_presets: DirectusPreset<Schema>[];
	axis_relations: DirectusRelation<Schema>[];
	axis_roles: DirectusRole<Schema>[];
	axis_settings: DirectusSettings<Schema>;
	axis_shares: DirectusShare<Schema>[];
	axis_users: DirectusUser<Schema>[];
	axis_versions: DirectusVersion<Schema>[];
}
