<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HCS.WebGateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\HCS.Bff\HCS.Bff.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Serilog" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Autofac" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Security" Version="10.6.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="HCS.WebGateway.Tests\**" />
    <Content Remove="HCS.WebGateway.Tests\**" />
    <EmbeddedResource Remove="HCS.WebGateway.Tests\**" />
    <None Remove="HCS.WebGateway.Tests\**" />
  </ItemGroup>

</Project>
