// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;
using hanhchinhso.DocumentService.Data;

#nullable disable

namespace hanhchinhso.DocumentService.Data.Migrations
{
    [DbContext(typeof(DocumentServiceDbContext))]
    [Migration("20260724155944_AddSigningExecution")]
    partial class AddSigningExecution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Volo.Abp.EntityFrameworkCore.DistributedEvents.IncomingEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<byte[]>("EventData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime?>("HandledTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("Status", "CreationTime");

                    b.ToTable("AbpEventInbox", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.EntityFrameworkCore.DistributedEvents.OutgoingEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<byte[]>("EventData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.ToTable("AbpEventOutbox", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReceiverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecrecyLevelId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UrgencyLevelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"Number\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"Number\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "OrganizationUnitId");

                    b.HasIndex("TenantId", "SourceType", "IncomingDate");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Documents.DocumentBlobCleanup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.HasIndex("TenantId", "BlobName")
                        .IsUnique();

                    b.ToTable("DocumentBlobCleanups", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Documents.DocumentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BlobDeletionPending")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<Guid?>("DerivedPdfFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SourceDocxFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SourceFileId");

                    b.HasIndex("TenantId", "BlobDeletionPending", "LastModificationTime");

                    b.HasIndex("TenantId", "DocumentId", "BlobName")
                        .IsUnique();

                    b.ToTable("DocumentFiles", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.SignatureSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowDigitalSign")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowElectronicSign")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ApiTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<int>("DefaultSignatureType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<bool>("EnableSignLog")
                        .HasColumnType("boolean");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("KeepOriginalFile")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("LayoutAssetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OverwriteSignedFile")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireOtp")
                        .HasColumnType("boolean");

                    b.Property<int>("SignHeight")
                        .HasColumnType("integer");

                    b.Property<int>("SignWidth")
                        .HasColumnType("integer");

                    b.Property<string>("SignedFileSuffix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("LayoutAssetId");

                    b.HasIndex("ProviderCode")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "ProviderCode")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("SignatureSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_SignatureSetting_DefaultSignatureType", "\"DefaultSignatureType\" IN (0, 1)");

                            t.HasCheckConstraint("CK_SignatureSetting_ExecutionLimits", "\"ApiTimeoutSeconds\" BETWEEN 1 AND 600 AND \"SignWidth\" BETWEEN 1 AND 2000 AND \"SignHeight\" BETWEEN 1 AND 2000");

                            t.HasCheckConstraint("CK_SignatureSetting_ProviderType", "\"ProviderType\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.SigningAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BlobDeletionPending")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "BlobName")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.HasIndex("TenantId", "OwnerUserId", "Kind");

                    b.ToTable("SigningAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_SigningAsset_KindOwner", "\"Kind\" IN (0, 1, 2) AND \"Size\" > 0 AND (\"Kind\" = 2 OR \"OwnerUserId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.SigningAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("ResultFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SignatureType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SignerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("UserSignatureConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserSignatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("ResultFileId");

                    b.HasIndex("SourceFileId");

                    b.HasIndex("UserSignatureId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.HasIndex("TenantId", "AssignmentId", "Status");

                    b.ToTable("SigningAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SigningAttempt_SignatureType", "\"SignatureType\" IN (0, 1)");

                            t.HasCheckConstraint("CK_SigningAttempt_StateShape", "(\"Status\" = 0 AND \"AttemptCount\" = 0 AND \"StartedAtUtc\" IS NULL AND \"FinishedAtUtc\" IS NULL AND \"ResultFileId\" IS NULL AND \"FailureCode\" IS NULL) OR (\"Status\" = 1 AND \"AttemptCount\" > 0 AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NULL AND \"ResultFileId\" IS NULL AND \"FailureCode\" IS NULL) OR (\"Status\" = 2 AND \"AttemptCount\" > 0 AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NOT NULL AND \"ResultFileId\" IS NOT NULL AND \"FailureCode\" IS NULL) OR (\"Status\" = 3 AND \"AttemptCount\" > 0 AND \"StartedAtUtc\" IS NOT NULL AND \"FinishedAtUtc\" IS NOT NULL AND \"ResultFileId\" IS NULL AND \"FailureCode\" IS NOT NULL) OR (\"Status\" = 4 AND \"FinishedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_SigningAttempt_Status", "\"Status\" IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.SigningBlobCleanup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("CreationTime");

                    b.HasIndex("TenantId", "BlobName")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("SigningBlobCleanups", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.UserSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("ProtectedSecret")
                        .HasColumnType("text");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SealAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignatureAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignatureSettingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SignatureType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("TokenReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ValidToUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SealAssetId");

                    b.HasIndex("SignatureAssetId");

                    b.HasIndex("SignatureSettingId");

                    b.HasIndex("TenantId", "ProviderCode");

                    b.HasIndex("TenantId", "IdentityUserId", "SignatureType", "IsActive");

                    b.ToTable("UserSignatures", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSignature_DigitalCredential", "\"SignatureType\" <> 1 OR NOT \"IsActive\" OR (\"TokenReference\" IS NOT NULL AND length(trim(\"TokenReference\")) > 0 AND \"ProtectedSecret\" IS NOT NULL AND length(trim(\"ProtectedSecret\")) > 0)");

                            t.HasCheckConstraint("CK_UserSignature_ElectronicCredential", "\"SignatureType\" <> 0 OR (\"TokenReference\" IS NULL AND \"ProtectedSecret\" IS NULL)");

                            t.HasCheckConstraint("CK_UserSignature_Type", "\"SignatureType\" IN (0, 1)");

                            t.HasCheckConstraint("CK_UserSignature_Validity", "\"ValidFromUtc\" IS NULL OR \"ValidToUtc\" IS NULL OR \"ValidToUtc\" >= \"ValidFromUtc\"");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CommittedStepId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<Guid?>("DocumentFileResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("CommittedStepId");

                    b.HasIndex("DocumentFileResultId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("InstanceId", "CommittedStepId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "InstanceId", "CommittedStepId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.HasIndex("TenantId", "ReceiverUserId", "Status", "IsCurrent");

                    b.ToTable("DocumentAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentAssignment_CurrentPending", "NOT \"IsCurrent\" OR \"Status\" = 0");

                            t.HasCheckConstraint("CK_DocumentAssignment_ProcessedShape", "((\"Status\" = 0 AND \"ProcessedAtUtc\" IS NULL) OR (\"Status\" IN (1, 2, 3) AND \"ProcessedAtUtc\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("TenantId", "DocumentId", "OccurredAtUtc");

                    b.ToTable("DocumentHistories", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedReceiver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommittedStepId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProvenanceOrganizationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProvenanceRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommittedStepId", "UserId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "CommittedStepId", "UserId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("DocumentWorkflowCommittedReceivers", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowReturn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SlaDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateStepId");

                    b.HasIndex("InstanceId", "Order")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("InstanceId", "TemplateStepId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "InstanceId", "Order")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.HasIndex("TenantId", "InstanceId", "TemplateStepId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("DocumentWorkflowCommittedSteps", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedViewScope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommittedStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommittedStepId", "OrganizationUnitId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"OrganizationUnitId\" IS NOT NULL");

                    b.HasIndex("CommittedStepId", "UserId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"UserId\" IS NOT NULL");

                    b.HasIndex("TenantId", "CommittedStepId", "OrganizationUnitId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"OrganizationUnitId\" IS NOT NULL");

                    b.HasIndex("TenantId", "CommittedStepId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentWorkflowCommittedViewScopes_TenantId_CommittedStep~1")
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"UserId\" IS NOT NULL");

                    b.ToTable("DocumentWorkflowCommittedViewScopes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommittedViewScope_OneTarget", "(\"OrganizationUnitId\" IS NOT NULL AND \"UserId\" IS NULL) OR (\"OrganizationUnitId\" IS NULL AND \"UserId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<Guid?>("CurrentCommittedStepId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeadlineAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("InitiatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OverdueAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PreviousInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SignMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int>("TotalExtensionBusinessDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCommittedStepId");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"Status\" IN (1, 2)");

                    b.HasIndex("PreviousInstanceId")
                        .IsUnique();

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowTemplateId");

                    b.HasIndex("TenantId", "DocumentId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"Status\" IN (1, 2)");

                    b.HasIndex("TenantId", "DocumentId", "Status");

                    b.ToTable("DocumentWorkflowInstances", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowInstance_ExtensionCounters", "\"ExtensionCount\" >= 0 AND \"TotalExtensionBusinessDays\" >= 0");

                            t.HasCheckConstraint("CK_WorkflowInstance_FinishedShape", "((\"Status\" IN (0, 1, 2) AND \"FinishedAtUtc\" IS NULL) OR (\"Status\" IN (3, 4, 5, 6) AND \"FinishedAtUtc\" IS NOT NULL))");

                            t.HasCheckConstraint("CK_WorkflowInstance_OverdueShape", "((\"Status\" = 2 AND \"OverdueAtUtc\" IS NOT NULL) OR (\"Status\" <> 2 AND \"OverdueAtUtc\" IS NULL))");
                        });
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("InstanceId");

                    b.HasIndex("TenantId", "InstanceId", "OccurredAtUtc");

                    b.ToTable("DocumentWorkflowInstanceLogs", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "WorkflowDefinitionId");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("WorkflowDefinitions", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("WorkflowStepTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WorkflowStepTemplateId");

                    b.HasIndex("WorkflowStepTemplateId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"IsPrimary\" = true AND \"IsActive\" = true AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "WorkflowStepTemplateId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowStepAssignmentConfigurations_TenantId_WorkflowStep~1")
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"IsPrimary\" = true AND \"IsActive\" = true AND \"IsDeleted\" = false");

                    b.ToTable("WorkflowStepAssignmentConfigurations", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentOrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId", "OrganizationUnitId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "ConfigurationId", "OrganizationUnitId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("WorkflowStepAssignmentOrganizationUnits", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId", "UserId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId", "ConfigurationId", "UserId")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL");

                    b.ToTable("WorkflowStepAssignmentUsers", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowReturn")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SlaDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "Order")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "WorkflowTemplateId", "Order")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("WorkflowStepTemplates", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("ContentSchema")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OutputFormat")
                        .HasColumnType("integer");

                    b.Property<string>("PdfTemplatePath")
                        .HasColumnType("text");

                    b.Property<int?>("SignMode")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("WordTemplatePath")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL AND \"IsDeleted\" = false");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId", "WorkflowId");

                    b.ToTable("WorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Documents.Document", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Documents.DocumentFile", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Documents.DocumentFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.SignatureSetting", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Signing.SigningAsset", null)
                        .WithMany()
                        .HasForeignKey("LayoutAssetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.SigningAttempt", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Documents.DocumentFile", null)
                        .WithMany()
                        .HasForeignKey("ResultFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hanhchinhso.DocumentService.Documents.DocumentFile", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Signing.UserSignature", null)
                        .WithMany()
                        .HasForeignKey("UserSignatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Signing.UserSignature", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Signing.SigningAsset", null)
                        .WithMany()
                        .HasForeignKey("SealAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hanhchinhso.DocumentService.Signing.SigningAsset", null)
                        .WithMany()
                        .HasForeignKey("SignatureAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Signing.SignatureSetting", null)
                        .WithMany()
                        .HasForeignKey("SignatureSettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentAssignment", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", null)
                        .WithMany()
                        .HasForeignKey("CommittedStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Documents.DocumentFile", null)
                        .WithMany()
                        .HasForeignKey("DocumentFileResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hanhchinhso.DocumentService.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentHistory", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedReceiver", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", null)
                        .WithMany("Receivers")
                        .HasForeignKey("CommittedStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", null)
                        .WithMany("Steps")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowStepTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedViewScope", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", null)
                        .WithMany("ViewScopes")
                        .HasForeignKey("CommittedStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", null)
                        .WithMany()
                        .HasForeignKey("CurrentCommittedStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hanhchinhso.DocumentService.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", null)
                        .WithOne()
                        .HasForeignKey("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", "PreviousInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hanhchinhso.DocumentService.Workflows.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstanceLog", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.Workflow", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentConfiguration", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowStepTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkflowStepTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentOrganizationUnit", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentConfiguration", null)
                        .WithMany("OrganizationUnits")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentUser", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentConfiguration", null)
                        .WithMany("Users")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepTemplate", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.WorkflowTemplate", null)
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowTemplate", b =>
                {
                    b.HasOne("hanhchinhso.DocumentService.Workflows.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowCommittedStep", b =>
                {
                    b.Navigation("Receivers");

                    b.Navigation("ViewScopes");
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.DocumentWorkflowInstance", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("hanhchinhso.DocumentService.Workflows.WorkflowStepAssignmentConfiguration", b =>
                {
                    b.Navigation("OrganizationUnits");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
