FROM mcr.microsoft.com/dotnet/sdk:10.0 AS base
USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app

FROM base AS final
WORKDIR /app

ENTRYPOINT ["dotnet", "HCS.Blazor.dll"]
