apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  appsettings.json: |-
    {
    "App": {
        "SelfUrl": "{{ include "abptestwithsso.hosts.blazorwebapp" . }}"
    },
    "AuthServer": {
        "Authority": "{{ include "abptestwithsso.hosts.authserver" . }}"
    },
    "RemoteServices": {
        "Default": {
          "BaseUrl": "{{ include "abptestwithsso.hosts.webgateway" . }}"
        },
        "AbpAccountPublic": {
          "BaseUrl": "{{ include "abptestwithsso.hosts.authserver" . }}"
        }
    }
    }