FROM mcr.microsoft.com/dotnet/aspnet:10.0
ARG APP_DLL
WORKDIR /app
COPY bin/Release/net10.0/publish/ ./
ENV APP_DLL=$APP_DLL ASPNETCORE_URLS=http://+:8080 DOTNET_EnableDiagnostics=0
USER $APP_UID
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "dotnet ${APP_DLL}"]
