<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>HCS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HCS.Application\HCS.Application.csproj" />
    <ProjectReference Include="..\..\src\HCS.HttpApi\HCS.HttpApi.csproj" />
    <ProjectReference Include="..\HCS.Domain.Tests\HCS.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.6.0" />
  </ItemGroup>

</Project>
