apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        ports:
        - name: "http"
          containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /app/wwwroot/appsettings.json
            subPath: appsettings.json
        env:
        - name: "DOTNET_ENVIRONMENT"
          value: "{{ .Values.global.dotnetEnvironment }}"
        - name: "App__SelfUrl"
          value: "{{ include "hanhchinhso.hosts.blazorwebapp" . }}"
        - name: App__EnablePII
          value: "{{ .Values.global.enablePII }}"
        - name: "App__ChatSignalrUrl"
          value: "http://{{ .Release.Name }}-blazorwebapp"
        - name: "Redis__Configuration"
          value: "{{ .Release.Name }}-redis"
        - name: "RemoteServices__Default__BaseUrl"
          value: "http://{{ .Release.Name }}-webgateway"
        - name: "RemoteServices__AbpAccountPublic__BaseUrl"
          value: "{{ include "hanhchinhso.hosts.authserver" . }}"
        - name: "AuthServer__Authority"
          value: "{{ include "hanhchinhso.hosts.authserver" . }}"
        - name: "AuthServer__MetaAddress"
          value: "http://{{ .Release.Name }}-authserver"
        - name: "AuthServer__RequireHttpsMetadata"
          value: "false"            
        - name: "AuthServer__IsOnK8s"
          value: "true" 
        - name: "AuthServer__ClientSecret"
          value: "{{ .Values.authServer.clientSecret }}"
        - name: "StringEncryption__DefaultPassPhrase"
          value: "{{ .Values.global.stringEncryptionDefaultPassPhrase }}"