
HCS_APPS_HOST=127.0.0.1
HCS_DATA_HOST=113.160.232.208
HCS_POSTGRES_HOST=113.160.232.208
HCS_MINIO_HOST=minio
HCS_REDIS_HOST=redis
HCS_RABBITMQ_HOST=rabbitmq

HCS_POSTGRES_WAIT_HOST=113.160.232.208
HCS_MINIO_WAIT_HOST=minio
HCS_REDIS_WAIT_HOST=redis
HCS_RABBITMQ_WAIT_HOST=rabbitmq

HCS_PUBLIC_HOST=hanhchinhso.benhvien199.vn
HCS_API_PUBLIC_HOST=api-hcs.benhvien199.vn
HCS_AUTH_PUBLIC_HOST=auth-hcs.benhvien199.vn
HCS_SSO_PUBLIC_HOST=sso-hcs.benhvien199.vn

Bff__CookieDomain=benhvien199.vn

HCS_DOCKER_REGISTRY=longnguyen1331/hanhchinhso
HCS_PULL_IMAGES=true

HCS_POSTGRES_USER=postgres
HCS_POSTGRES_PASSWORD=Bv199

HCS_REDIS_PASSWORD=Bv199

HCS_RABBITMQ_USER=guest
HCS_RABBITMQ_PASSWORD=guest

HCS_MINIO_ROOT_USER=hcsadmin
HCS_MINIO_ROOT_PASSWORD=hcsadminpassword
HCS_MINIO_BUCKETNAME=hcsbucket
HCS_ADMIN_PASSWORD=9W5HBnrenM2R2ad5l4pt9RChR1

HCS_GATEWAY_CLIENT_SECRET=dev-gateway-client-secret-2026

HCS_KEYCLOAK_ADMIN=admin
HCS_KEYCLOAK_ADMIN_PASSWORD=dev-keycloak-admin-2026
HCS_KEYCLOAK_CLIENT_SECRET=loANPSFTnaUyu6RsSM3wtlW6LLDTVolB

# Baota panel path
HCS_OPENIDDICT_PFX=/www/server/panel/data/compose/qldh-free/.hcs-certs/openiddict.pfx
HCS_OPENIDDICT_PFX_PASSWORD=dev-openiddict-pfx-password

HCS_DATAPROTECTION_PFX=/www/server/panel/data/compose/qldh-free/.hcs-certs/dataprotection.pfx
HCS_DATAPROTECTION_PFX_PASSWORD=dev-dataprotection-pfx-password

HCS_SKIP_PORT_WAIT=true

HCS_MOBILE_CLIENT_ID=hcs-mobile
HCS_MOBILE_REDIRECT_URI=com.htltech.hcs:/oauth/callback
HCS_MOBILE_POST_LOGOUT_REDIRECT_URI=com.htltech.hcs:/oauth/logout

ConnectionStrings__DocumentService=User ID=postgres;Password=Bv199;Host=postgres;Port=5432;Database=AxisHCS;Pooling=false;

AuthServer__Authority=https://localhost:44401

Minio__EndPoint=localhost:9000
Minio__AccessKey=hcsadmin
Minio__SecretKey=hcsadminpassword
